### PR TITLE
Fix super feature/publish modal issues

### PR DESCRIPTION
**Pull request by kand**

### CODE REVIEW

**Comment by kand** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;3vgaz065&#x2F;116-fix-publish-modal-issues-new-relation-ordering"> Fix publish modal issues, new relation ordering</a>

**Comment by kand** [comment]
@daytonn @collin

**Comment by daytonn** [comment]
Could `send-to-editor-modal.js` be flattened out a little. It seems overly nested to me. My head starts to swim once I get a couple levels in. Looking at the link example [here](https://docs.angularjs.org/guide/directive) it seems like this example is more readable.

**Comment by daytonn** [comment]
👍

**Pull request merged**
