### PR TITLE
add hide_from_rss checkbox

### PR DESCRIPTION
**Pull request by MichaelButkovic**
@kand @spra85 @MelizzaP @daytonn @collin

### CODE REVIEW

**Comment by kand** [comment]
Can we write a test for this? Pretty trivial, but I wanna get new code tested.

I can help out Monday if you need.

**Comment by MelizzaP** [comment]
lgtm, and +1 on testin' it

**Comment by spra85** [comment]
👍, ditto on the tests

**Comment by kand** [comment]
👍

**Pull request merged**
