### PR TITLE
fix firebase data access errors

### PR DESCRIPTION
**Pull request by kand**

### CODE REVIEW

**Comment by kand** [comment]
@collin @daytonn @mparent61 @MelizzaP

**Comment by kand** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YF3UH3b2&#x2F;148-js-error-about-client-not-being-allowed-to-access-desired-data"> js error about client not being allowed to access desired data</a>

**Comment by mparent61** [comment]
Failing tests make me hesitant to merge this while @kand is out, new path containing `.../sites/sites/...` seems fishy: 

```
AssertionError: expected '/home/travis/build/theonion/bulbs-cmsio.com/sites/sites/onion/123' to equal '/home/travis/build/theonion/bulbs-cmsio.com/sites/onion/123'
```

**Comment by kand** [comment]
Closing this PR, this is not the correct fix. Will update all sites so their `FIREBASE_ROOT` contains `sites`.

**Pull request closed without merging**
