### PR TITLE
Config zencoder path

### PR DESCRIPTION
**Pull request by benghaziboy**
@kand @collin 

Video changes create a need to configure zencoder paths across sites.

### CODE REVIEW

**Comment by benghaziboy** [comment]
@collin 

@kand, this was prepending the domain twice in the cms. Seemingly only ever used for embeds, but I am uncertain if you are using it elsewhere.

**Comment by kand** [comment]
Is the zencoder endpoint on the site's server now? Originally it must have been located elsewhere and needed to have a root url.

**Comment by benghaziboy** [comment]
https://github.com/theonion/omni/blob/master/clickhole/clickhole/production.py

It is configured to the same site's domain && the onsite zencoder is the older version. Maybe an update when we were trying to separate bulbs-cms?

**Comment by kand** [comment]
Okay, as long as it's working now? I don't believe we're using it anywhere else.

**Comment by benghaziboy** [comment]
👍

**Pull request merged**
