### PR TITLE
add tests for static-image and fix url issue

### PR DESCRIPTION
**Pull request by kand**

### CODE REVIEW

**Comment by kand** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ajmNXPBD&#x2F;589-webtech-av-club-cms-bug-report-adding-an-image-to-a-review"> [WEBTECH] AV Club CMS Bug Report - adding an image to a review</a>

**Comment by kand** [comment]
@collin @daytonn @spra85

**Comment by collin** [comment]
👍

**Comment by daytonn** [comment]
👍

**Pull request merged**
