### PR TITLE
Live Blogs - show created user and timestamp in entries

### PR DESCRIPTION
**Pull request by kand**
Live Blog entries should show the time an entry was first created as well as the user that created it. 

**Release Type**: _patch_
No large-scale new features, mostly moving and adding small amounts of code. Evaluated sites for usages of breaking changes and none should be so affected that the CMS breaks if left unaddressed.

**New**

1. Added `CurrentUserApi` under `bulbs.cms.currentUser.api`, provides non-restmod access to the current user api.

2. `live-blog-entries` directive will show which user created a entry and when it was created. Will also display the user and when the entry was last updated.

3. Added a `mixin-text-muted` less mixin for muted text, available in base CMS code by importing `mixins/_mixin-text`.

**Updates**

1. `LiveBlogApi` transforms `created` and `updated` date time fields to and from backend.

2. `live-blog-entries` directive now aware of `created_by`, `created`, `updated_by`, and `updated` fields.

3. All usages of `CurrentUser` service in base CMS code switched to `CurrentUserApi`.

4. All usages of `user` filter in base CMS code switched to `userNameDisplay` filter.

5. `logged-in-user` directive now shows loading text while current user info is being retrieved.

6. Removed unnecessary image minification build task.

7. Removed unused `LocalStorageBackup` service tests.

**Breaking**

1. `nav-bar` directive no longer provides `current_user` on the scope. Sites using a navbar html that accesses `current_user.data` should now access `currentUser` instead.

2. `user` filter changed to `userNameDisplay` and moved into `bulbs.cms.currentUser.nameDisplayFilter`, now lives alongside `CurrentUserApi` and both are available under `bulbs.cms.currentUser`. Usage of `user` in code should be changed to `userNameDisplay`.

3. `CurrentUser` service removed, use `CurrentUserApi` instead.

### CODE REVIEW

**Comment by kand** [comment]
@mparent61 @collin @daytonn @MelizzaP please review.

**Comment by kand** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wQvwKWFJ&#x2F;59-dry-run-findings"> Dry Run Findings</a>

**Comment by daytonn** [comment]
seems legit, it's a lot of stuff but nothing sticks out 👍

**Comment by collin** [comment]
👆 👍 🎳

**Pull request merged**
